version: '3'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=email@example.com
    volumes:                     
      - .:/etc/nginx/conf.d
networks:
  default:
    external:
      name: nginx-proxy