version: '3'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      # - LETSENCRYPT_HOST=site2.com
      # - LETSENCRYPT_EMAIL=email@site2.com
    volumes:                     
      - .:/etc/nginx/conf.d
      - ../../html:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy