version: "3"
services:
  php-fpm:
    build: ./build/php7.4-fpm
    container_name: php7.4-fpm
    restart: always
    volumes:
      - ../html:/usr/share/nginx/html
      - ./config/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    expose:
      - 9000
      
networks:
  default:
    external:
      name: nginx-proxy
